config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('rooms/', include('rooms.urls', namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from rooms.views import HomeView

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = 'rooms'

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django_countries.fields import CountryField
from core.models import AbstractTimestamp

User = settings.AUTH_USER_MODEL


class AbstarctItemModel(models.Model):
    name = models.CharField(max_length=140)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstarctItemModel):
    pass

    class Meta:
        verbose_name = "Room Type"


class Amenity(AbstarctItemModel):
    pass

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstarctItemModel):
    pass

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstarctItemModel):
    pass

    class Meta:
        verbose_name = "House Rule"


class Photo(AbstarctItemModel):
    caption = models.CharField(max_length=80)
    file = models.ImageField()
    room = models.ForeignKey(
        'Room', on_delete=models.CASCADE, related_name='photos')


class Room(AbstractTimestamp):
    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="rooms")
    room_type = models.ForeignKey(
        RoomType, null=True, on_delete=models.SET_NULL, related_name="rooms")
    amenities = models.ManyToManyField(
        Amenity, blank=True, related_name="rooms")
    facilities = models.ManyToManyField(
        Facility, blank=True, related_name="rooms")
    house_rules = models.ManyToManyField(
        HouseRule, blank=True, related_name="rooms")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})
    
    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)
        return 0
    
    def first_photo(self):
        try:
            photo, = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos

    def get_beds(self):
        if self.beds == 1:
            return "1 bed"
        else:
            return f"{self.beds} beds"

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()
    
class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import Http404
from django.contrib.messages.views import SuccessMessageMixin
from django_countries import countries
from .models import Room, RoomType, Amenity, Facility, Photo
from . import forms
from users import mixins as user_mixins


class HomeView(ListView):
    model = Room
    paginate_by = 10
    paginate_orphans = 5
    ordering = 'created'
    context_object_name = 'rooms'
    template_name = 'rooms/home.html'

class RoomDetail(DetailView):
    model = Room
    context_object_name = 'room'
    template_name = 'rooms/room_detail.html'


class SearchView(View):

    """ SearchView Definition """

    def get(self, request):

        country = request.GET.get("country")

        if country:

            form = forms.SearchForm(request.GET)

            if form.is_valid():

                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = Room.objects.filter(**filter_args).order_by("-created")

                paginator = Paginator(qs, 10, orphans=5)

                page = request.GET.get("page", 1)

                rooms = paginator.get_page(page)

                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )

        else:
            form = forms.SearchForm()

        return render(request, "rooms/search.html", {"form": form})


class EditRoomView(user_mixins.LoggedInOnlyView,UpdateView):

    model = Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room

@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Cant delete that photo")
        else:
            Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo Deleted")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except Room.DoesNotExist:
        return redirect(reverse("core:home"))

class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    fields = ("caption",)

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})

class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):

    template_name = "rooms/photo_create.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(self.request, "Room Uploaded")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/home.html
{% extends 'base.html' %}

{% block title %} All Rooms {% endblock title %}

{% block content %}
{% if rooms %}
    {% for room in rooms %}
        <h3><a href="{{ room.get_absolute_url }}">{{ room.name }} | {{ room.city }} | ${{ room.price }}</a></h3>
        <p>{{ room.description }}</p>
    {% endfor %}
    {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}
    <h5>
        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
    </h5>
    {% if page_obj.has_next  %}
        <a href="?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}
{% else %}
    <h1>There's no Rooms to display...</h1>
{% endif %}
{% endblock content %}

templates/rooms/photo_create.html
{% extends "base.html" %}

{% block page_title %}
    Upload photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Upload photo" %}

    </div>
{% endblock content %}

templates/rooms/photo_edit.html
{% extends "base.html" %} {% block page_title %} Update photo {% endblock
page_title %} {% block search-bar %} {% endblock search-bar %} {% block content
%}

<div
  class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400"
>
  {% include 'mixins/room/room_form.html' with form=form cta="Update photo" %}
</div>
{% endblock content %}

templates/rooms/room_create.html
{% extends "base.html" %} {% block page_title %} Create Room {% endblock
page_title %} {% block search-bar %} {% endblock search-bar %} {% block content
%}

<div
  class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400"
>
  {% include 'mixins/room/room_form.html' with form=form cta="Create room" %}
</div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %} {% block page_title %} {{room.name}} {% endblock
page_title %} {% block content %}

<div class="-mt-5 container max-w-full h-75vh flex mb-20">
  <div
    class="h-full w-1/2 bg-center bg-cover"
    style="background-image:url({{room.first_photo}})"
  ></div>
  <div class="h-full w-1/2 flex flex-wrap">
    {% for photo in room.get_next_four_photos %}
    <div
      style="background-image:url({{photo.file.url}})"
      class="w-1/2 h-auto bg-cover bg-center border-gray-700 border"
    ></div>
    {% endfor %}
  </div>
</div>

<div class="container mx-auto flex justify-around pb-56">
  <div class="w-1/2">
    <div class="flex justify-between">
      <div class="mb-5">
        <h4 class="text-3xl font-medium mb-px">{{room.name}}</h4>
        <span class="text-gray-700 font-light">{{room.city}}</span>
      </div>
      <a
        href="{{room.host.get_absolute_url}}"
        class="flex flex-col items-center"
      >
        {% include "mixins/user_avatar.html" with user=room.host %}
        <span class="mt-2 text-gray-500">{{room.host.first_name}}</span>
      </a>
    </div>
    <div class="flex border-section">
      <span class="mr-5 font-light">{{room.room_type}}</span>
      <span class="mr-5 font-light"
        >{{room.beds}} bed{{room.beds|pluralize}}</span
      >
      <span class="mr-5 font-light"
        >{{room.bedrooms}} bedroom{{room.bedrooms|pluralize}}</span
      >
      <span class="mr-5 font-light"
        >{{room.baths}} bath{{room.baths|pluralize}}</span
      >
      <span class="mr-5 font-light"
        >{{room.guests}} guest{{room.guests|pluralize}}</span
      >
    </div>
    <p class="border-section">{{room.description}}</p>
    <div class="border-section">
      <h4 class="font-medium text-lg mb-5">Amenities</h4>
      {% for a in room.amenities.all %}
      <li class="mb-2">{{a}}</li>
      {% endfor %}
    </div>
    <div class="border-section">
      <h4 class="font-medium text-lg mb-5">Facilities</h4>
      {% for a in room.facilities.all %}
      <li class="mb-2">{{a}}</li>
      {% endfor %}
    </div>
    <div class="border-section">
      <h4 class="font-medium text-lg mb-5">House Rules</h4>
      {% for a in room.house_rules.all %}
      <li class="mb-2">{{a}}</li>
      {% endfor %}
    </div>
    <div class="border-section">
      <h4 class="font-medium text-2xl mb-5">Reviews</h4>
      <div>
        {{room.total_rating}} {{room.reviews.count}}
        review{{room.reviews.count|pluralize}}
      </div>
    </div>
  </div>
  <div class="w-1/3"></div>
  <div class="w-1/3">
    {% if room.host == user %}
    <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block"
      >Edit Room</a
    >
    {% endif %}
  </div>
</div>

{% endblock %}

templates/rooms/room_edit.html
{% extends "base.html" %} 
{% block page_title %} Update Room {% endblock
page_title %} 
{% block search-bar %} {% endblock search-bar %} 
{% block content %}

<div
  class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400"
>
  {% include 'mixins/room/room_form.html' with form=form cta="Update room" %}

    <div class="mt-5">
            <a href="{% url 'rooms:photos' room.pk %}" class="text-teal-500 font-medium">Edit Photos</a>
        </div>
</div>
{% endblock content %}

templates/rooms/room_form.html
<form method="POST" class="w-full" enctype="multipart/form-data">
  {% csrf_token %} {% if form.non_field_errors %} {% for error in
  form.non_field_errors %}
  <span class="text-red-700 font-medium text-sm">{{error}}</span>
  {% endfor %} {% endif %} {% for field in form %} {% include
  'mixins/room/room_input.html' with field=field %} {% endfor %}

  <button class="btn bg-red-500 text-white">{{cta}}</button>
</form>

templates/rooms/room_input.html
<div class="input w-full {% if field.errors %}has_error{% endif %}">
  {{field.label}} {{field}} {% if field.errors %} {% for error in field.errors
  %}
  <span class="text-red-700 font-medium text-sm">{{error}}</span>
  {% endfor %} {% endif %}
</div>

templates/rooms/room_photos.html
{% extends "base.html" %}

{% block page_title %}
    {{room.name}}'s Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container mx-auto my-10 flex flex-col">
        <div class="my-10 w-full">
            <a href="{% url 'rooms:add-photo' room.pk %}" class="btn-link w-1/6 block">Upload Photo</a>
        </div>
        
        {% for photo in room.photos.all  %}
            <div class="mb-5 border p-6 border-gray-400 flex justify-between">
                <div class="flex items-start">
                    <img src="{{photo.file.url}}" class="w-32 h-32" />
                    <span class="ml-5 text-xl">{{photo.caption}}</span>
                </div>
                <div class="flex flex-col w-1/5">
                    <a class="btn-link mb-5 bg-teal-500" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">Edit</a>
                    <a class="btn-link bg-red-600" href="{% url 'rooms:delete-photo' room.pk photo.pk %}">Delete</a>
                </div>
            </div>
        {% endfor %}

        <div class="flex justify-center mt-5">
            <a href="{% url 'rooms:edit' room.pk %}" class="text-teal-500 font-medium text-xl">Back to edit room</a>
        </div>

    </div>
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block title %}
    Search
{% endblock title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <h2>Search!</h2>

    <form method="get" action="{% url "rooms:search" %}">
        {{form.as_p}}
        <button>Search</button>
    </form>

    <h3>Results</h3>

    {% for room in rooms %}
        <h3>{{room.name}}</h3>
    {% endfor %}


{% endblock content %}